services:
  - type: web
    name: bank-frontend
    env: static
    buildCommand: npm run build
    staticPublishDir: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
